language: objective-c
osx_image: xcode7.2

env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="MKNetworkKit-iOS"
  - OSX_FRAMEWORK_SCHEME="MKNetworkKit-Mac"
  - TVOS_FRAMEWORK_SCHEME="MKNetworkKit-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="MKNetworkKit-watchOS"
  - IOS_SDK=iphonesimulator9.1
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.0   
  - WATCHOS_SDK=watchsimulator2.1
  - DEMO_SCHEME="MKNetworkKitDemo"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" 
    - DESTINATION="OS=8.2,name=iPhone 5"        SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.3,name=iPhone 5S"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.4,name=iPhone 6"        SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"    
    - DESTINATION="arch=x86_64"                 SCHEME="$OSX_FRAMEWORK_SCHEME" SDK="$OSX_SDK"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"  SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$TVOS_SDK"
    - DESTINATION="OS=2.1,name=Apple Watch - 38mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace MKNetworkKit.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
  - xcodebuild -workspace MKNetworkKit.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c

notifications:
  email: false